name: CI/CD Pipeline

on:
  push:
    branches:
      - master    # or 'main' if that's your default branch

jobs:
  build-test-release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Lint code
      run: |
        pylint app.py

    - name: Run static analysis
      run: |
        bandit app.py || true

    - name: Run tests with coverage
      run: |
        coverage run -m unittest discover
        coverage report

    - name: Build Docker image
      run: |
        docker build -t my-flask-app:latest .

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Tag and push Docker image
      run: |
        docker tag my-flask-app:latest ${{ secrets.DOCKER_USERNAME }}/my-flask-app:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/my-flask-app:latest
    - name: Run static analysis
      run: |
        bandit -r . --severity-level high




