name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: Set up python 3.10
        uses: actions/Setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8 black pylint pytest

      - name: Lint code with flake8
        run: 
          flake8 . --exclude=venv

      - name: Check code formatting with balck
        run: black --check . --exclude=venv
          
