name: CI

on:
  push:
    branches:
      - master

jobs:
  build and test:
    runs-on: ubuntu:latest


    strategy:
      matrix:
        python-version: 3.9

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
